tpm: In DRBG_IV union, define words member to size DRBG_IV_SIZE_WORDS.
Having the two union members defined as arrays of different sizes will
cause pedantic compilers to complain about possible undefined behavior
when accessed through the smaller array. Declaring these arrays with the
intended size makes things a bit more clear / verbose and keeps the
compiler happy.

The issue was identified using gcc & CFLAGS = -Wall -Werror:
TPMCmd/tpm/src/crypt/CryptRand.c:139:31: error: iteration 1 invokes undefined behavior [-Werror=aggressive-loop-optimizations]
         dfState->buf.words[i] = 0;
         ~~~~~~~~~~~~~~~~~~~~~~^~~
TPMCmd/tpm/src/crypt/CryptRand.c:138:5: note: within this loop
     for(i = 0; i < DRBG_IV_SIZE_WORDS; i++)
     ^~~
TPMCmd/tpm/src/crypt/CryptRand.c:134:51: error: iteration 1 invokes undefined behavior [-Werror=aggressive-loop-optimizations]
             temp[i] ^= pIv[i] ^ dfState->buf.words[i];
                                 ~~~~~~~~~~~~~~~~~~^~~
TPMCmd/tpm/src/crypt/CryptRand.c:132:9: note: within this loop
         for(i = 0; i < DRBG_IV_SIZE_WORDS; i++)
         ^~~
TPMCmd/tpm/src/crypt/CryptRand.c:139:27: error: array subscript is above array bounds [-Werror=array-bounds]
         dfState->buf.words[i] = 0;
         ~~~~~~~~~~~~~~~~~~^~~
TPMCmd/tpm/src/crypt/CryptRand.c:139:27: error: array subscript is above array bounds [-Werror=array-bounds]
TPMCmd/tpm/src/crypt/CryptRand.c:139:27: error: array subscript is above array bounds [-Werror=array-bounds]
cc1: all warnings being treated as errors

Signed-off-by: Philip Tricca <philip.b.tricca@intel.com>